[phases.setup]
nixPkgs = ["ruby_3_3", "postgresql"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "gem install bundler:2.7.0",
  "bundle install"
]

[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}"