[phases.setup]
nixPkgs = ["ruby_3_3", "postgresql", "libxml2", "libxslt", "pkg-config"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "gem install bundler:2.7.0",
  "bundle config set --local deployment false",
  "bundle config set --local frozen false",
  "bundle install --jobs 4 --retry 3"
]

[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}"